# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-15 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mercadoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(max_length=4)),
                ('tipo_mercadoria', models.TextField(blank=True, max_length=20, null=True)),
                ('nome', models.TextField(blank=True, max_length=30, null=True)),
                ('quantidade', models.IntegerField(max_length=8)),
                ('preco', models.CharField(max_length=10)),
                ('tipo_negocio', models.TextField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
