# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-17 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boi', '0004_auto_20170917_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercadoria',
            name='tipo_negocio',
            field=models.CharField(blank=True, choices=[('Compra', 'Compra'), ('Venda', 'Venda')], max_length=20, null=True),
        ),
    ]
